version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./backend:/app
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./backend:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    db:
        image: mysql:5.7
        ports:
            - "33061:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
        volumes:
          - db:/var/lib/mysql

    frontend:
        command: "sh /start.sh"
        build:
            context: .
            dockerfile: ./js/Dockerfile
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"

volumes:
  db: